const { description } = require('../../package')

module.exports = {
  /**
   * Ref：https://v1.vuepress.vuejs.org/config/#title
   */
  title: 'Vuepress Docs Boilerplate',
  /**
   * Ref：https://v1.vuepress.vuejs.org/config/#description
   */
  description: description,

  /**
   * Extra tags to be injected to the page HTML `<head>`
   *
   * ref：https://v1.vuepress.vuejs.org/config/#head
   */
  head: [
    ['meta', { name: 'theme-color', content: '#3eaf7c' }],
    ['meta', { name: 'apple-mobile-web-app-capable', content: 'yes' }],
    ['meta', { name: 'apple-mobile-web-app-status-bar-style', content: 'black' }]
  ],

  /**
   * Theme configuration, here is the default theme configuration for VuePress.
   *
   * ref：https://v1.vuepress.vuejs.org/theme/default-theme-config.html
   */
  themeConfig: {
    repo: '',
    editLinks: false,
    docsDir: '',
    editLinkText: '',
    lastUpdated: false,
    nav: [
      {
        text: 'Themes',
        link: '/themes/',
      }
    ],
    sidebar: {
      '/themes/': [
        {
          title: "Vuepress Themes",
          children: [
            'vuepress-theme-yur',
            'vuepress-theme-api-starter-kit',
            'vuepress-theme-jupiter',
            'vuepress-theme-craftdocs',
            'vuepress-theme-foundation',
            'vuepress-theme-mini',
            'vuepress-theme-track',
            'vuepress-theme-succinct',
            'vuepress-theme-pinghsu',
            'vuepress-theme-sakura',
            'vuepress-theme-ant',
            'vuepress-theme-reco',
            'vuepress-theme-loaded',
            'vuepress-theme-yilia-plus',
            'vuepress-theme-ououe-template',
            'vuepress-theme-dark',
            'vuepress-theme-kitdocs',
            'vuepress-theme-sponge',
            'vuepress-theme-canvas',
            'vuepress-theme-ermu',
            'vuepress-theme-multi',
            'vuepress-theme-reco-demo',
            'vuepress-theme-cute',
            'vuepress-theme-tsugumori',
            'vuepress-theme-clair',
            'vuepress-theme-indigo-material',
            'vuepress-theme-limitless-ping',
            'vuepress-theme-talltotal',
            'vuepress-theme-panda',
            'vuepress-theme-postline',
            'vuepress-theme-brandeur',
            'vuepress-theme-starry',
            'vuepress-theme-x',
            'vuepress-theme-lite',
            'vuepress-theme-prettyPure',
            'vuepress-theme-nui',
            'vuepress-theme-vuepress',
            'vuepress-theme-bootstrap',
            'vuepress-theme-cosmos',
            'vuepress-theme-fluent',
            'vuepress-theme-simple',
            'vuepress-theme-monokai',
            'vuepress-theme-xhh',
            'vuepress-theme-ads',
            'vuepress-theme-egoist',
            'vuepress-theme-sammyne',
            'vuepress-theme-gocommons',
            'vuepress-theme-idg',
            'vuepress-theme-lemon',
            'vuepress-theme-egg',
            'vuepress-theme-asshole',
            'vuepress-theme-blogue',
            'vuepress-theme-vango',
            'vuepress-theme-live-ebook',
            'vuepress-theme-interactive',
            'vuepress-theme-shadow',
            'vuepress-theme-tassel',
            'vuepress-theme-lovely',
            'vuepress-theme-cola',
            'vuepress-theme-xydocs',
            'vuepress-theme-fuaa',
            'vuepress-theme-isonaj',
            'vuepress-theme-zjblog',
            'vuepress-theme-kim',
            'vuepress-theme-cbin',
            'vuepress-theme-glitzma',
            'vuepress-theme-typewriter',
            'vuepress-theme-happy',
            'vuepress-theme-blog',
            'vuepress-theme-yubisaki',
            'vuepress-theme-viola',
            'vuepress-theme-meteorlxy',
            'vuepress-theme-zjy',
            'vuepress-theme-koala',
            'vuepress-theme-default-prefers-color-scheme',
            'vuepress-theme-ting',
            'vuepress-theme-modern-blog',
            'vuepress-theme-elegant',
            'vuepress-theme-starter2',
            'vuepress-theme-ououe',
            'vuepress-theme-ken',
            'vuepress-theme-teadocs',
            'vuepress-theme-demo',
            'vuepress-theme-cycle',
            'vuepress-theme-oscarteg',
            'vuepress-theme-story',
            'vuepress-theme-material',
            'vuepress-theme-lovelife',
            'vuepress-theme-indigo',
            'vuepress-theme-buzheng',
            'vuepress-theme-cky',
            'vuepress-theme-oneN',
            'vuepress-theme-ldy',
            'vuepress-theme-ebook',
            'vuepress-theme-musubii',
            'vuepress-theme-pretty',
            'vuepress-theme-chaves',
            'vuepress-theme-casper',
            'vuepress-theme-jian',
            'vuepress-theme-note',
            'vuepress-theme-one',
            'vuepress-theme-britecore',
            'vuepress-theme-mufeng',
            'vuepress-theme-valle',
            'vuepress-theme-vuescroll',
            'vuepress-theme-blogvis',
            'vuepress-theme-blog-official-style',
            'vuepress-theme-homesite',
            'vuepress-theme-concise',
            'vuepress-theme-terminal',
            'vuepress-theme-taewoong',
            'vuepress-theme-luna',
            'vuepress-theme-refrom-reco',
            'vuepress-theme-gh-style',
            'vuepress-theme-light',
            'vuepress-theme-bb',
            'vuepress-theme-hope',
            'vuepress-theme-biubiu',
            'vuepress-theme-next',
            'vuepress-theme-flipbox',
            'vuepress-theme-bhabgs',
            'vuepress-theme-daily',
            'vuepress-theme-neptune',
            'vuepress-theme-blogvis-demo',
            'vuepress-theme-monday',
            'vuepress-theme-seeker',
            'vuepress-theme-melody',
            'vuepress-theme-vook',
            'vuepress-theme-codemao_docs',
            'vuepress-theme-learner',
            'vuepress-theme-dew',
            'vuepress-theme-reform',
            'vuepress-theme-dong',
            'vuepress-theme-yur-cli',
            'vuepress-theme-cool',
            'vuepress-theme-tsed',
            'vuepress-theme-hhh',
            'vuepress-theme-dynamicsidebar',
            'vuepress-theme-neon',
            'vuepress-theme-thindark',
            'vuepress-theme-even',
            'vuepress-theme-meteorlxy-original',
            'vuepress-theme-yubisaki-example',
            'vuepress-theme-component-catalog',
            'vuepress-theme-macgs',
            'vuepress-theme-preper',
            'vuepress-theme-whilife',
            'vuepress-theme-starter1',
            'vuepress-theme-modern-portfolio',
            'vuepress-theme-medium',
            'vuepress-theme-trskillblog',
            'vuepress-theme-madd-docs',
            'vuepress-theme-single-page-sections',
            'vuepress-theme-Secondary_element',
            'vuepress-theme-mdc',
            'vuepress-theme-meteorlxy-cwr',
            'vuepress-theme-tomato',
            'vuepress-theme-nav',
            'vuepress-theme-dark-new',
            'vuepress-theme-nativescript-vue',
            'vuepress-theme-cchao',
            'vuepress-theme-piero',
            'vuepress-theme-resume',
            'vuepress-theme-default-hot',
            'vuepress-theme-blogly',
            'vuepress-theme-nine',
            'vuepress-theme-travis',
            'vuepress-theme-yubisaki-debug',
            'vuepress-theme-bulma',
            'vuepress-theme-aloe',
            'vuepress-theme-zp',
            'vuepress-theme-bobo',
            'vuepress-theme-blog-tohutohu',
            'vuepress-theme-vuejs-berlin',
            'vuepress-theme-vuetify',
            'vuepress-theme-gouv-fr',
            'vuepress-theme-antd',
            'vuepress-theme-yuicer',
            'vuepress-theme-similar-yilia',
            'vuepress-theme-hope-docs-beta',
            'vuepress-theme-docs',
            'vuepress-theme-kalisio',
            'vuepress-theme-millidocs',
            'vuepress-theme-eugeo',
            'vuepress-theme-zeit',
            'vuepress-theme-bgcz',
            'vuepress-theme-dew-demo',
            'vuepress-theme-easyBlog',
            'vuepress-theme-vest',
            'vuepress-theme-cool-starter',
            'vuepress-theme-nature-aventure',
            'vuepress-theme-tabsp',
            'vuepress-theme-uzkk',
            'vuepress-theme-yuu',
            'vuepress-theme-crow',
            'vuepress-theme-zero',
            'vuepress-theme-test',
            'vuepress-theme-kytest',
            'vuepress-theme-ktquez-starter',
            'vuepress-theme-yobrave',
            'vuepress-theme-cityseer',
            'vuepress-theme-simple-blog',
            'vuepress-theme-ktquez',
            'vuepress-theme-default',
            'vuepress-theme-lost',
            'vuepress-theme-ajv',
            'vuepress-theme-api'
          ]
        }
      ],
    }
  },

  /**
   * Apply plugins，ref：https://v1.vuepress.vuejs.org/zh/plugin/
   */
  plugins: [
    '@vuepress/plugin-back-to-top',
    '@vuepress/plugin-medium-zoom',
  ]
}
