const { description } = require('../package')

module.exports = {
  /**
   * Ref：https://v1.vuepress.vuejs.org/config/#title
   */
  title: 'Vuepress Tools',
  /**
   * Ref：https://v1.vuepress.vuejs.org/config/#description
   */
  description: description,

  /**
   * Extra tags to be injected to the page HTML `<head>`
   *
   * ref：https://v1.vuepress.vuejs.org/config/#head
   */
  head: [
    ['meta', { name: 'theme-color', content: '#3eaf7c' }],
    ['meta', { name: 'apple-mobile-web-app-capable', content: 'yes' }],
    ['meta', { name: 'apple-mobile-web-app-status-bar-style', content: 'black' }],
    ['link', { rel: "apple-touch-icon", sizes: "180x180", href: "/apple-touch-icon.png" }],
    ['link', { rel: "icon", type: "image/png", sizes: "32x32", href: "/favicon-32x32.png" }],
    ['link', { rel: "icon", type: "image/png", sizes: "16x16", href: "/favicon-16x16.png" }],
    ['link', { rel: "manifest", href: "/site.webmanifest" }],
    ['link', { rel: "mask-icon", href: "/safari-pinned-tab.svg", color: "#5bbad5" }],
    ['meta', { name: "msapplication-TileColor", content: "#da532c" }],
    ['meta', { name: "theme-color", content: "#ffffff" }]
  ],

  /**
   * Theme configuration, here is the default theme configuration for VuePress.
   *
   * ref：https://v1.vuepress.vuejs.org/theme/default-theme-config.html
   */
  themeConfig: {
    repo: '/arab-open-source/vuepress-tools',
    logo: '/img/vuepress-tools-logo.png',
    editLinks: false,
    docsDir: '',
    editLinkText: '',
    lastUpdated: false,
    author: 'Ahmad Mostafa',
    domain: 'vuepress.tools',
    nav: [
      {
        text: 'Home',
        link: '/',
        icon: 'home'
      },
      {
        text: 'Themes',
        link: '/themes/',
        icon: 'palette'
      },
      {
        text: 'Plugins',
        link: '/plugins/',
        icon: 'plug'
      }
    ],
    sidebar: {
      '/themes/': [
        "cox",
        "interactive",
        "musubii",
        "tassel",
        "Secondary_element",
        "craftdocs",
        "jian",
        "nature-aventure",
        "teadocs",
        "ads",
        "crow",
        "jupiter",
        "nav",
        "terminal",
        "ajv",
        "cute",
        "kalisio",
        "neon",
        "thindark",
        "alisa",
        "cycle",
        "ken",
        "neptune",
        "ting",
        "ant",
        "dark-new",
        "kim",
        "nine",
        "tomato",
        "api",
        "dark",
        "kitdocs",
        "note",
        "track",
        "apidoc",
        "default-hot",
        "koala",
        "one",
        "travis",
        "asshole",
        "default-prefers-color-scheme",
        "ktquez",
        "oneN",
        "trskillblog",
        "bb",
        "default",
        "ldy",
        "openapi",
        "tsed",
        "bgcz",
        "dew",
        "learner",
        "oscarteg",
        "tsugumori",
        "bhabgs",
        "docs",
        "lemon",
        "ououe",
        "typewriter",
        "blog-official-style",
        "dong",
        "light",
        "oyiadin",
        "uzkk",
        "blog-tohutohu",
        "dynamicsidebar",
        "liuli",
        "piero",
        "valle",
        "blog",
        "easyBlog",
        "live-ebook",
        "pinghsu",
        "viola",
        "blogue",
        "ebook",
        "loaded",
        "postline",
        "vook",
        "blogvis",
        "egg",
        "lomo",
        "pretty",
        "vuejs-berlin",
        "bobo",
        "egoist",
        "lost",
        "purple",
        "vuepress",
        "bootstrap",
        "elegant",
        "lovelife",
        "reco",
        "vuescroll",
        "box",
        "ermu",
        "lovely",
        "reform",
        "vuetify",
        "britecore",
        "eugeo",
        "luna",
        "refrom-reco",
        "whilife",
        "bulma",
        "even",
        "macgs",
        "resume",
        "x",
        "buzheng",
        "flipbox",
        "material",
        "sakura",
        "xhh",
        "canvas",
        "fluent",
        "mdc",
        "sammyne",
        "xydocs",
        "casper",
        "foundation",
        "medium",
        "seeker",
        "yilia-plus",
        "cbin",
        "funtask",
        "melody",
        "shadow",
        "yobrave",
        "cchao",
        "gh-style",
        "meteorlxy-cwr",
        "similar-yilia",
        "yubisaki",
        "challenges",
        "glitzma",
        "meteorlxy-original",
        "simple-blog",
        "yuchanns",
        "chaves",
        "gocommons",
        "meteorlxy",
        "simple-bulma",
        "yuicer",
        "cky",
        "gouv-fr",
        "millidocs",
        "simple",
        "yur-cli",
        "clair",
        "hhh",
        "mini",
        "single-page-sections",
        "yur",
        "codemao_docs",
        "homesite",
        "modern-blog",
        "starry",
        "yuu",
        "cola",
        "hope",
        "modern-portfolio",
        "succinct",
        "zeit",
        "component-catalog",
        "ic",
        "monday",
        "system",
        "zero",
        "concise",
        "idg",
        "monokai",
        "tabsp",
        "zjblog",
        "cool",
        "indigo-material",
        "moon",
        "taewoong",
        "zjy",
        "cosmos",
        "indigo",
        "mufeng",
        "talltotal",
        "zp",
      ],
      '/plugins/': [
        "clipboard-copy",
        "element-ui",
        "image",
        "named-chunks",
        "screenfull",
        "additionalPages-sample",
        "code-block",
        "enhanced-search",
        "img-lazy",
        "nest",
        "search",
        "alias",
        "code-box",
        "example-preview",
        "import-code",
        "netscope",
        "selected-text-popup",
        "amazon-global-tracking",
        "code-copy",
        "export-site",
        "import-codes",
        "new",
        "seo",
        "amp",
        "code-doc",
        "export-to-pdf",
        "ipfs",
        "nprogress",
        "serve",
        "api-docs-generator",
        "code-segment",
        "export",
        "janitor",
        "one-click-copy",
        "server-push",
        "application-insights",
        "code-switcher",
        "extract-code",
        "kan-ban-niang",
        "pagation",
        "share",
        "authors",
        "comment",
        "featured",
        "latex",
        "pagination",
        "sidebar-on-off",
        "auto-sidebar",
        "comments",
        "feed",
        "live",
        "pdfjs",
        "sidebar",
        "autometa",
        "component-catalog",
        "firebase",
        "live2d",
        "permalink-pinyin",
        "simple-seo",
        "autonav",
        "component-docgen",
        "fish",
        "loading-page",
        "sitemap",
        "back-to-top",
        "contact-us",
        "flexsearch",
        "mailchimp",
        "podcast",
        "smooth-scroll",
        "baidu-autopush",
        "container",
        "flowchart",
        "markdown-classes",
        "ppt",
        "social-share",
        "baidu-tongji",
        "contributors",
        "ga",
        "mathjax-bug8",
        "prism",
        "spacing",
        "bgm-player",
        "copyright",
        "gettext",
        "mathjax",
        "qihu-autopush",
        "svg-icons",
        "blog-advance",
        "cpt",
        "git-log",
        "matomo",
        "raml-loader",
        "table-of-contents",
        "blog-comment-demo",
        "crisp",
        "gitalk-maker",
        "mdx",
        "reading-progress",
        "tabs",
        "blog-multidir",
        "cursor-effects",
        "gitalk",
        "media",
        "reading-time",
        "tailwind",
        "blog-test",
        "define",
        "global-toc",
        "medium-zoom",
        "redirect",
        "toc",
        "blog",
        "dehydrate",
        "go-top",
        "merge-pages",
        "remote-url",
        "transformer",
        "boxx",
        "demo-block",
        "google-adsense",
        "mermaid",
        "reward",
        "viewer",
        "canonical",
        "demo-code",
        "google-analytics",
        "mermaidjs",
        "ribbon",
        "visit",
        "cat",
        "disqus-comment",
        "google-tag-manager",
        "migrate",
        "robots",
        "yuque-deploy",
        "check-md",
        "disqus",
        "gotop-plus",
        "minimal-analytics",
        "rocket",
        "yuque",
        "clean-urls",
        "docgen",
        "helper-live2d",
        "miniprogram",
        "rpurl",
        "zooming",
        "cleanmylink",
        "dynamic-title",
        "hotjar",
        "mouse-effects",
        "rss",
        "click",
        "element-tabs",
        "i18n-ui",
        "mygitalk",
        "run",
      ]
    }
  },

  /**
   * Apply plugins，ref：https://v1.vuepress.vuejs.org/zh/plugin/
   */
  plugins: [
    ['@vuepress/plugin-back-to-top'],
    ['@vuepress/plugin-medium-zoom'],
    [
      'sitemap', {
        hostname: 'https://vuepress.tools'
      }
    ],
    ['seo'],
    ['flexsearch'],
    require.resolve('./setTitle')
  ]
}
